### ISSUE TITLE
fix resolution

### ISSUE THREAD

**Issue by AndreSHeyde** [ajcao/MakeDueDemo#18]

**Comment by ajcao** [comment]
https://docs.unity3d.com/ScriptReference/Camera.WorldToScreenPoint.html

https://docs.unity3d.com/ScriptReference/Camera.ScreenToWorldPoint.html

**Comment by AndreSHeyde** [comment]
https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/HOWTO-UIMultiResolution.html#:~:text=Scaling%20with%20Screen%20Size&text=With%20this%20scale%20mode%20you,together%20with%20the%20screen%20resolution.

**Comment by AndreSHeyde** [comment]
Change is pushed on resolution-fix branch. Tested the change in different scenes with HD (1920 x 1080) resolution vs 4K (3840 x 2160) and validated position and size scaling with each change. Also validated that interacting with the scenes seemed to be functioning properly in both resolutions. More playtesting may uncover issues, but so far I think this can be resolved after someone tries it out.
